### ISSUE TITLE
Cowboy normalization

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#116]
There are some things we should probably ‘cowboy normalize’ with Primo rules like series titles (8xx,4xx), but doing this type of normalizing for every possible instance would require making hundreds of rules and would be time consuming.  A less time-consuming option is to consider disabling some titles and cowboy normalizing some key ones.

Also: see Ben Florin's email from 11/13/13 about this issue.

**Comment by sarahjeansweeney** [comment]
2/28/14 Email from Stephanie: 
As requested, Sarah and I have been trying a little bit of “cowboy normalization” on the Primo title browse results in the test environment to thin out the results that sort by initial article. For starters, we removed unauthorized series titles (field 490) from the title browse. It doesn’t solve the entire problem of initial articles in the browse search and results, but I think it’s a good first step. [Below] are before and after screen shots showing what the removal of the 490s looks like.

Please let us know if you’d like us to remove the 490 fields from the title browse in production.

BTW, besides creating a problem with initial articles, I feel strongly that 490 series headings (which are not meant to be “added entries” in any case) in the title browse mislead patrons by suggesting we have less material in a given series than we might actually have, since the titles can fluctuate from volume to volume. Authorized headings bring these all together reliably, and we have retained authorized headings in the browse.  Also, we have not eliminated unauthorized series headings from the general keyword search where they are still very valuable.

The remaining problem records in the browse that sort by initial article are brief Community Zone records without indicators in the 245. Sarah and I have tried several ways to force Primo to ignore leading articles in the 245 without luck just yet. More to come on this.

Title browse in Production 2/26/14:
![production](https://f.cloud.github.com/assets/4663073/2338592/361708de-a4ab-11e3-8570-3b8ca6df1f0f.png)

Title browse in Test 2/16/14 with rule in place to remove untraced/unauthorized series entries (as you can see, the first seven entries that appeared in production are gone):
![staging](https://f.cloud.github.com/assets/4663073/2338593/38e5b150-a4ab-11e3-979d-8b278cff6413.png)

**Comment by sarahjeansweeney** [comment]
I removed the unauthorized series titles (field 490) from the title browse in production. The next step is for Stephanie to review what other fields can be removed from the title browse. Once we remove as many fields as possible, she and I will work on "cowboy" normalizing the remaining fields.

**Comment by winthropo** [comment]
Awesome. Thanks.

**Comment by nestochan** [comment]
@winthropo @jasf- @sarahjeansweeney can this be closed?
