### ISSUE TITLE
Advanced Search Bug

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#135]
Do a simple search in SOS (starting from SOS not Library homepage) then click on Advanced Search ... SOS offers the advanced screen but you have to scroll up to see it. 

You can see the buggy behavior here:

http://www.screencast.com/t/RpdCS5eJiI

Seems to only happen when the search starts from SOS itself and not from the Library homepage. 

Desired behavior is here:

http://www.screencast.com/t/PFhPxaCH5

**Comment by kmerguerian** [comment]
A similar problem occurs when you do a OneSearch on an iPhone with Safari.  The results page displays at about the fifth result, and you have to SCROLL UP to get to the top of the list.

**Comment by elizoller** [comment]
I think this is due to role="main" which is an ARIA landmark to aid in accessibility for users with screen readers. Different browsers tend to interpret this differently. Ie. Chrome 37 jumps down to the content with role="main", Firefox 32 does not.
In terms of actual usage of landmarks, there was a study done by webaim which showed that about 56% of screen reader users do not use landmarks for navigation or did not know that the functionality existed. See http://webaim.org/projects/screenreadersurvey3/#landmarks for more info.
Webaim notes that the skip navigation links are "a rather clumsy and obtrusive solution" and recommends simply using the proper headings (h1, h2, etc.) to allow a non-sighted user the ability to scan through an "outline" based on the headings (http://webaim.org/techniques/skipnav/).
Best practices for accessibility seem to conclude that until modern browsers fully adapt new HTML5 elements (such as main), it is best to continue to use ARIA landmarks (roles) and skip to main content links.

**Comment by elizoller** [comment]
In order not to go against best practices, I just added a line to load the page at the top. 4a9c7f1f060dd76f53b852871727a63f150e2344

**Comment by winthropo** [comment]
Looks good! Thanks.
