### ISSUE TITLE
SOS sandbox: search and drop-down buttons not aligned

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#141]
Sandbox on 4.8.2

![screen shot 2014-09-08 at 10 47 52 am](https://cloud.githubusercontent.com/assets/4663357/4187151/379cb7b8-3767-11e4-9f0f-37dbdd61f7cf.png)

**Comment by jasf-** [comment]
Pretty.

**Comment by elizoller** [comment]
This is due to a "clear search" button feature being turned on in the Sandbox. Adding CSS to that element will fix this easily.

**Comment by elizoller** [comment]
Fixed in [dev view](http://onesearch-test.northeastern.edu/primo_library/libweb/action/search.do?vid=NUdev) by c26eacd888f73c1966565aa7e2d3558098e46a11

**Comment by elizoller** [comment]
When the clear button renders, it by default was covered by the search button due to the buttons being floated to the right. 
Fixed by pushing to the left 8512eeeb896567c6a758a7acf2245d0d288c807c
![screen shot 2014-10-14 at 12 10 33 pm](https://cloud.githubusercontent.com/assets/5439169/4632344/acf517dc-53bc-11e4-802b-ebdbcb220552.png)
