### ISSUE TITLE
Reword "Search WorldCat" link in SOS 

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#145]
Change to:

"Search other libraries" with WorldCat logo

![screen shot 2014-09-10 at 3 58 29 pm](https://cloud.githubusercontent.com/assets/4663357/4224432/146abad2-3925-11e4-9b73-25385be9296e.png)

**Comment by elizoller** [comment]
Fixed in dev by d4505bf3b64e3a743a37ddffdad7c33cecb822e5
See http://onesearch-test.library.northeastern.edu/primo_library/libweb/action/search.do?fn=search&ct=search&initialSearch=true&mode=Basic&tab=default_tab&indx=1&dum=true&srt=rank&vid=NUdev&frbg=&vl%28freeText0%29=test&scp.scps=scope%3A%28NEU%29%2Cprimo_central_multiple_fe
