### ISSUE TITLE
Facet not working

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#163]

**Comment by kmerguerian** [comment]
Do a search, such as "educational testing". 

Click on facet "books".  This considerably decreases the result list from 102, 000 to 2,000.  However the remaining results are still a combination of articles and books from our collection.

**Comment by elizoller** [comment]
Is that because the scope was on Library Catalog + Articles?
When I did educational testing search then limited to books, I was also seeing articles mixed in but when I changed the dropdown scope to Library Catalog and then limited to books, it was a true book search. 
It's like the book facet with Library Catalog + Articles literally did all of the books in the library catalog + Articles.

**Comment by kmerguerian** [comment]
Interesting observation! But it should work like in production...not sure who knows how to fix or if this is a call to Ex Libris?

**Comment by elizoller** [comment]
It does not appear to be working in production either...?

**Comment by nestochan** [comment]
@elizoller @kmerguerian  This is most definitely a Case to open with  EXlibris.
BC and Brandeis has the same issue. I can't see a problem in the facet section of the PNX that would make them fall into a book facet. but they are all PCI titles.--  as noted local collections are fine.

:black_joker:
