### ISSUE TITLE
Scoping on new journal title search

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#166]
You need to be on "library catalogs" for the journal title search to work.  Have that scope locked down as the journal material type is locked down.

**Comment by elizoller** [comment]
I went into the Journal View and edited the default tab to reorder the scopes so Library Catalog was on top. I added JS (b0a4276c80f3c19a8c0d19593488365d9420c3db) to disable that dropdown (I didn't see a way to do this through the Back End because the scopes are not the same as the other fields like material type). I edited the Journal View to use the blank static htmls instead of the `nu_news.html` and `nu_featured.html` which is what generates the static content under the search box.

![screen shot 2014-11-07 at 3 11 47 pm](https://cloud.githubusercontent.com/assets/5439169/4959640/56341b1c-66ba-11e4-8816-e18caf3b9fdd.png)

Does that look right?

**Comment by jdevanna** [comment]
looks good to me.

**Comment by jasf-** [comment]
Agreed.

**Comment by elizoller** [comment]
@kmerguerian @winthropo  are we good on this?

**Comment by winthropo** [comment]
looks good.
