### ISSUE TITLE
eShelf and item type displaying above record in iOS

### ISSUE THREAD

**Issue by jdevanna** [NEU-Libraries/scholar-onesearch#172]
- Screenshot:
  ![image](https://cloud.githubusercontent.com/assets/9257706/5857788/5070f126-a21c-11e4-8df5-3f8d1ff8433a.png)
- URL: http://onesearch.library.neu.edu/primo_library/libweb/action/search.do?fn=search&ct=search&initialSearch=true&mode=Basic&tab=default_tab&indx=1&dum=true&srt=rank&vid=NU&frbg=&vl%28freeText0%29=test&scp.scps=scope%3A%28NEU%29%2Cprimo_central_multiple_fe
- Browser: Chrome and Safari on iOS
- Description: The item type and eshelf items are displaying above the record instead of to the left of the record in Chrome and Safari on iOS (ipad and iphone)

**Comment by elizoller** [comment]
This is a result of screen width (not related to browsers/OS)
We basically have it set right now so that the block that contains the details (title, author, etc is one column) and on a large screen it takes up 3/4 of the width and on a medium screen it takes up the full width and on an extra small screen it takes up full width. 
We can modify the medium size width so that on iPad, it will be less wide but still sit up next to its thumbnail and e-shelf icon.

**Comment by elizoller** [comment]
@jasf- @winthropo @jdevanna 
I forgot to bring this up in READ - I have pushed this to NUdev
It is a slight modification of the breakpoints so that on a medium screen the details will still float to the right instead of wrapping to underneath- the wrapping will occur on a smaller screen.

**Comment by elizoller** [comment]
Since it was minor, I deployed it but if you see any issues let me know.
