### ISSUE TITLE
Permalinks not working in SoS link resolution page

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#174]
Example:

Find this journal article in CINAHL
http://ezproxy.neu.edu/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=ccm&AN=2012792819&site=ehost-live&scope=site

Click on "Check for Full Text"
Go to "Permalink" on the resulting SoS page
Paste the permalink into another browser.  You get the blank SoS screen with the little yellow dot. 

This is happening to me in iOS with Safari and Firefox. 
![screen shot 2015-03-24 at 6 03 39 pm](https://cloud.githubusercontent.com/assets/2442078/6813807/174280a0-d24f-11e4-920a-35b4178e332c.png)

**Comment by elizoller** [comment]
I think this might be because when I do a search directly for this article in SoS it doesn't show up that we have it so then the permalink function can't find an item with that id. 
I'm not really sure why it doesn't show up in SoS but if you go through CINAHL, we do have it? Maybe @jdevanna can explain it to me?

**Comment by kmerguerian** [comment]
Yes I noticed that also--Maybe we should not offer a permalink in this situation then?

Karen Merguerian
User Services
Northeastern University Libraries

On Mar 25, 2015, at 8:01 AM, "Eli Zoller" <notifications@github.com<mailto:notifications@github.com>> wrote:

I think this might be because when I do a search directly for this article in SoS it doesn't show up that we have it so then the permalink function can't find an item with that id.
I'm not really sure why it doesn't show up in SoS but if you go through CINAHL, we do have it? Maybe @jdevannahttps://github.com/jdevanna can explain it to me?

##

**Comment by jdevanna** [comment]
I think what's going on here is that the metadata being passed through the link resolver is creating a "temporary" record, basically just a display of the metadata, somehow the permalink function is creating an id when the permalink is generated, however since it is not actually a record in primo, there is no way to link back to it. There would need to be someway to actually pass the URL of the initial open URL request into the report a problem form instead of the permalink when it is not actually a record in primo, if that makes sense

For example, the only way to link back to the record generated by the link resolver is:

http://onesearch.library.northeastern.edu/primo_library/libweb/action/openurl?dscnt=1&genre=article&spage=1094&sid=EBSCO%3ACINAHL+Complete&isSerivcesPage=true&url_ctx_fmt=null&issn=10286020&issue=11&pages=1094-1098&dstmp=1427287006153&date=20141101&aulast=Hussain%2C+Hidayat&atitle=Coniothyren%3A+a+new+phenoxyphenyl+ether+from+the+endophytic+fungus%2C+Coniothyrium+sp.&title=Journal+of+Asian+Natural+Products+Research&isbn=&volume=16&vid=neu_services_page&doi=10.1080%2F10286020.2014.931843&institution=NEU&fromLogin=true

I have no idea how the system is generating:

http://onesearch.library.northeastern.edu/NU:RS_6102860201094hyticfungusconiothyriumsp

I'll open a case with ExLibris to see if they can explain how this is generated.

**Comment by elizoller** [comment]
I believe the string comes from NU being the view id and after the colon is the id of the .EXLResultRecordId item in the result dom. So it's some kind of unique identifier per result. Not sure where that id is generated by EXL though

**Comment by kmerguerian** [comment]
That makes perfect sense!  But from a user viewpoint we can't be offering a permalink that is in fact a temporary link. Thanks for offering to open a ticket.

Karen Merguerian
User Services
Northeastern University Libraries

On Mar 25, 2015, at 8:39 AM, "jdevanna" <notifications@github.com<mailto:notifications@github.com>> wrote:

I think what's going on here is that the metadata being passed through the link resolver is creating a "temporary" record, basically just a display of the metadata, somehow the permalink function is creating an id when the permalink is generated, however since it is not actually a record in primo, there is no way to link back to it. There would need to be someway to actually pass the URL of the initial open URL request into the report a problem form instead of the permalink when it is not actually a record in primo, if that makes sense

For example, the only way to link back to the record generated by the link resolver is:

http://onesearch.library.northeastern.edu/primo_library/libweb/action/openurl?dscnt=1&genre=article&spage=1094&sid=EBSCO%3ACINAHL+Complete&isSerivcesPage=true&url_ctx_fmt=null&issn=10286020&issue=11&pages=1094-1098&dstmp=1427287006153&date=20141101&aulast=Hussain%2C+Hidayat&atitle=Coniothyren%3A+a+new+phenoxyphenyl+ether+from+th e+endoph ytic+fungus%2C+Coniothyrium+sp.&title=Journal+of+Asian+Natural+Products+Research&isbn=&volume=16&vid=neu_services_page&doi=10.1080%2F10286020.2014.931843&institution=NEU&fromLogin=truehttp://onesearch.library.northeastern.edu/primo_library/libweb/action/openurl?dscnt=1&genre=article&spage=1094&sid=EBSCO%3ACINAHL+Complete&isSerivcesPage=true&url_ctx_fmt=null&issn=10286020&issue=11&pages=1094-1098&dstmp=1427287006153&date=20141101&aulast=Hussain%2C+Hidayat&atitle=Coniothyren%3A+a+new+phenoxyphenyl+ether+from+the+endophytic+fungus%2C+Coniothyrium+sp.&title=Journal+of+Asian+Natural+Products+Research&isbn=&volume=16&vid=neu_services_page&doi=10.1080%2F10286020.2014.931843&institution=NEU&fromLogin=true

I have no idea how the system is generating:

http://onesearch.library.northeastern.edu/NU:RS_6102860201094hyticfungusconiothyriumsp

I'll open a case with ExLibris to see if they can explain how this is generated.

##

**Comment by elizoller** [comment]
Should I disable permalink functionality on the neu_services_page view?

**Comment by kmerguerian** [comment]
Question for READ perhaps?

Karen Merguerian
User Services
Northeastern University Libraries

On Mar 25, 2015, at 8:51 AM, "Eli Zoller" <notifications@github.com<mailto:notifications@github.com>> wrote:

Should I disable permalink functionality on the neu_services_page view?

##

**Comment by jdevanna** [comment]
It sometimes provides a portion of the article title which allows me to search and pull up a related record, so it is somewhat useful

**Comment by elizoller** [comment]
I'm also only able to get the permalink to work one time in the same browser. So it's not exactly permanent.

**Comment by winthropo** [comment]
I think we should disable the SOS permalink we get coming from CINHAL etc. The permalink in SOS seems to be working fine.

**Comment by elizoller** [comment]
Deployed
