### ISSUE TITLE
Search alert email links not working

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#175]
See below, from my weekly search alert.  When I try to link to the article below, I get a nice message asking me to sign in, so far so good.

After I sign in, I still don't see the citation, I just get another message to please sign in.  I've attached a screenshot (sorry it's in word).

Firefox in windows 7, from off-campus.
Safari in MacOSX on campus

---

From: library@neu.edu library@neu.edu
Sent: Friday, March 27, 2015 12:00 AM
To: Merguerian, Gayane Karen
Subject: New search results: libraries AND assessment, catalog and articles

There are new items in your saved search:199

Note that 25 items are included in this email.

[Lots of stuff deleted here]

From nsdl 1.0 to nsdl 2.0: towards a comprehensive cyberinfrastructure for teaching and learning
http://onesearch.northeastern.edu/primo_library/libweb/action/dlDisplay.do?docId=TN_acm1378902&loc=adaptor,primo_central_multiple_fe&vid=NU&tab=default_tab

![2015-03-27_14-28-12](https://cloud.githubusercontent.com/assets/2442078/6874296/837c90be-d48c-11e4-80a4-a038c6d10243.png)

**Comment by elizoller** [comment]
This is not caused by our customizations as I just tested the behavior on the out of the box primo view and had the same results - infinitely being asked to sign in.
I'm also fairly certain this isn't just related to the links that are generated by the email because I manually searched for this article and click permalink and ran into the same issue. 
In this particular case I don't think we have access to this item at all so I'm wondering if that's why permalink doesn't work? Or if it has something to do with scope because it's coming from primo central index?

**Comment by kmerguerian** [comment]
Opened ExLibris Salesforce case #00142431

**Comment by elizoller** [comment]
Looking at the Release Notes for the April 2015 Primo Release and I'm seeing a fix labelled "Permalinks to Primo Central records that did not have full text displayed an error. This has been fixed." So maybe ExL has already taken on this issue.
