### ISSUE TITLE
Search bar error when switched to e-shelf

### ISSUE THREAD

**Issue by jdevanna** [NEU-Libraries/scholar-onesearch#180]
- Screenshot: ![search_box_jumble](https://cloud.githubusercontent.com/assets/9257706/7090765/64e73bee-df73-11e4-87ba-03f4add08843.png)
- URL: http://onesearch-test.library.northeastern.edu/primo_library/libweb/action/basket.do?fn=display&fromUserArea=true&vid=NU&fromPreferences=false
- Browser: All browsers
- Description: Go to e-journal finder, add first journal to the e-shelf, click on e-shelf link in top right corner of the page, note the search box gets all jumbled.

**Comment by elizoller** [comment]
To replicate this I had to go to the Advanced Search or the Journal Title Search before going to the e-journal finder and following the steps you provided. I think it's because the e-Shelf carries in whatever search you were on before the E-journal finder (whether it was simple or advanced).
I'm going to look into this more.

**Comment by elizoller** [comment]
I checked out this flow in the NU_CLEAN view because I was curious if it was a problem with our CSS/JS or not. I thought it could be because we do a lot of heavy styling on those areas.
But I've discovered it is an issue with Primo out of the box.
Advanced Search in NU_CLEAN:
![screen shot 2015-04-13 at 10 33 33 am](https://cloud.githubusercontent.com/assets/5439169/7117726/b4f3f40e-e1c8-11e4-9973-f4c29719feff.png)
E-shelf (after clicking advanced then e-journal a-z then e-shelf) attempts to carry in advanced search but kind of fails:
![screen shot 2015-04-13 at 10 35 03 am](https://cloud.githubusercontent.com/assets/5439169/7117739/c4f9e20a-e1c8-11e4-90b7-f85b8fd6b75b.png)
It changes the advanced search into a more simple search with just the search field and the search scope because the field you're searching on and the material types are disabled.
So maybe this is intended behavior? I'm not sure but I'm going to try to override this css so it'll look like the simple search again by hiding the disabled options and realigning the boxes.
