### ISSUE TITLE
Permalinks resolving to error screen

### ISSUE THREAD

**Issue by jdevanna** [NEU-Libraries/scholar-onesearch#185]
- Screenshot: ![2015-04-30_1034](https://cloud.githubusercontent.com/assets/9257706/7415099/aa350cd8-ef24-11e4-82f8-734b0d81563e.png)
- URL: http://onesearch.northeastern.edu/NU:NEU_ALMA51209600070001401&tabs=viewOnlineTab
- Browser: Chrome 42 on Windows
- Description: Some permalinks have been resolving to the error screen above. Here is another example from today's library help email:

http://onesearch.library.neu.edu/NU:TN_gale_ofa409043494

**Comment by jdevanna** [comment]
clicking the search button brings up the record though

**Comment by jdevanna** [comment]
may have been something exlibris did...

**Comment by kmerguerian** [comment]
The links in my weekly search alerts are usually broken.  I've been complaining about this for a long time, there's a ticket #158 for a similar issue in staging and we also have a salesforce ticket 00142431 in which the tech claims it will be fixed in the "April release" but I'm not sure which release he is talking about.

**Comment by elizoller** [comment]
April release does not mean 4.9 (the release we're actually working on now). So we do not have this supposed fix right now in staging.

**Comment by jasf-** [comment]
Yep, Eli's got it.  'April release' in Ex Libris-speak = 4.9.1.  We're deploying 4.9 in April.  Confusing.
