### ISSUE TITLE
Rename 'reviews & tags' and make Actions menu display in tab? 

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#191]
From Laurence Lockton at University of Bath's post to primo-discuss-l.  Might this be worth doing to help users find the emailing, saving, and export to citation management functions more easily?  

No action is necessary on this now; I'm just memorializing it in a ticket for discussion by READ.

"I renamed the “Reviews & Tags” tab to “Save/Share” and made the Actions menu display in the tab by changing CSS. I have not tested whether users find it more easily though.
http://primo.bath.ac.uk/"

![saveshareprimo](https://cloud.githubusercontent.com/assets/4661920/8210669/0b933c5c-14e1-11e5-8b67-acb708a5722b.png)

**Comment by jasf-** [comment]
@elizoller - what's your sense for how hard this might be to do?

**Comment by elizoller** [comment]
what would save/share replace for us?

**Comment by elizoller** [comment]
Oh you mean like move the actions menu into a tab that is named save/share?

**Comment by jasf-** [comment]
Yes exactly!  Scott is going to darken your door to discuss - easier to look at than explain.

**Comment by elizoller** [comment]
Looking at this more closely, it looks like Bath moved the 'actions' menu on the Reviews & Tags tab to be sort of exposed in the tab itself. Since the actions menu isn't formulated until someone clicks on one of the tabs, we could probably re-show the reviews and tabs tab (which we had hidden with css) and then override the functionality so that it isn't a true tab anymore and just triggers a dropdown that has the actions menu from the reviews tab. Definitely do-able just a little tricky. But this way we aren't having to manually formulate the links which would make a little fragile.

**Comment by jasf-** [comment]
READ's in favor of trying the Bath model, pretty much just as Bath did it (except less pink).

**Comment by elizoller** [comment]
Do you still want the actual content of the reviews tab hidden?

**Comment by jasf-** [comment]
Not necessarily.  We hid that tab long ago because at the time, the contents seemed useless/redundant to us.  If you think using the reviews/tabs tab to display the actions menu is the way to go, let's give it a whirl!

**Comment by elizoller** [comment]
Ok. Thanks

**Comment by jasf-** [comment]
No, thank YOU for putting up with my stupid comment "like Bath but less pink" :smiling_imp:

**Comment by jasf-** [comment]
I think we can probably close this one as the new UI will accomplish most of this.
