### ISSUE TITLE
SOS Advanced Search/Journal Title Search

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#215]
To reproduce this:
1. Start from the library home page. 
2. Click on the Advanced link in the Scholar OneSearch box of the Library home page. 
3. Click on the Journal Title Search link in the Advanced Search red box. 
4. Return to the Library home page. 
5. Click on the Advanced link in the Scholar ONeSearch box

You will notice it brings you, not to the advanced search, but to the Journal Title Search again. Sticks.

This seems to stick when you click on Advanced Search in SOS, too.

**Comment by elizoller** [comment]
The links on the homepage did not previous include the vid so if you went to the journal title list the vid changes to nu_journals. I guess the vid is being remembered by sos so when you go back to advanced it defaults to the last vid you were on. Patching homepage links now so that they include NU vid so it will always go to NU advanced.

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/library-drupal/commit/fcbe1706b09387aee51cdfbd692870ca70da6557
