### ISSUE TITLE
Northeastern University Libraries logo

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#239]
This is for getting a library logo in the upper left hand corner in prod and sandbox. It would be really nice if was clickable like in the old ui and brought the user back to: http://library.northeastern.edu/

![upperleftlogo](https://cloud.githubusercontent.com/assets/4663357/21934833/efb928f8-d978-11e6-93b2-282d01203370.png)

**Comment by elizoller** [comment]
In the old UI we have two logos the library logo which points to library.northeastern.edu and the scholarone logo which points to scholarone homepage - would you like to maintain this functionality?
<img width="411" alt="screen shot 2017-01-13 at 12 18 02 pm" src="https://cloud.githubusercontent.com/assets/5439169/21938713/73132eae-d98a-11e6-81a7-ecc6ea54563c.png">
(sorry for bad screenshot but i think you get the idea)

**Comment by winthropo** [comment]
Yes. My bad. Should have been clearer. Lets keep that functionality.

**Comment by kmerguerian** [comment]
Working now in the test instance, thanks!

**Comment by winthropo** [comment]
The SOS link brings user to the oldUI.

**Comment by elizoller** [comment]
I did that on purpose because eventually onesearch-test.northeastern.edu will point to the new UI. Would you rather it point to http://northeastern-primostaging.hosted.exlibrisgroup.com/primo-explore/search?vid=NUdev&sortby=rank&lang=en_US ?

**Comment by winthropo** [comment]
Not necessarily. Sounds like you have a good plan. OK to close this ticket?

**Comment by elizoller** [comment]
Hmm.. maybe I will change this - that way I have staging still point to staging and it'd be easier to get back to the homepage of the new UI that way.

**Comment by winthropo** [comment]
That's sort of what I was thinking, but for our testing purposes it isn't critical. If the other way is somehow easier for you fine with me.

**Comment by elizoller** [comment]
Not any more difficult - I'll change it soon

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/scholar-onesearch/commit/bc350d30571308c5d65220a26b851bf571411009 https://github.com/NEU-Libraries/scholar-onesearch/commit/02e7c09a1b1836abe32be61e7cfeb7142150cd79 https://github.com/NEU-Libraries/scholar-onesearch/commit/77b82a798265a6ac52e4bc2f72993ceb74df3507

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/scholar-onesearch/commit/bc350d30571308c5d65220a26b851bf571411009 https://github.com/NEU-Libraries/scholar-onesearch/commit/02e7c09a1b1836abe32be61e7cfeb7142150cd79 https://github.com/NEU-Libraries/scholar-onesearch/commit/77b82a798265a6ac52e4bc2f72993ceb74df3507
