### ISSUE TITLE
Material Type label mismatch

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#240]
Does it bother anyone that the mouseover label for Material Type is "rtype"? Long ago, as you know, we relabeled the Resource Type facet "Material Type." 

How would you fix it? Remove the "rtype" from the mouseover? Rename "rtype" "mtype"?

![rtype](https://cloud.githubusercontent.com/assets/4663357/21937108/f43e6e96-d983-11e6-8824-ab866178eabd.png)

**Comment by elizoller** [comment]
This feels like they've exposed the machine name for these elements and it either corresponds to a label or the template needs to be modified to grab the human readable name instead of the machine name. I would say rtype should read "Material Type" as that is the designated human readable name. I'll look into it after I get some of the more major features set up.

**Comment by winthropo** [comment]
Yep. Thanks. 

Most don't match and some are worse than others. Course Reserves is "local1" Availability is "tlevel"

**Comment by winthropo** [comment]
This doesn't need to get fixed until we go live in the summer I think...

**Comment by gam5** [comment]
I would guess that they've added new labels in a mapping table somewhere. Probably an easy fix in the Back Office.
