### ISSUE TITLE
Hide item barcodes in new UI

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#244]
Hidden barcodes didn't carry over into new UI. I assume READ wants to continue this practice and hide the barcode in the new UI. Any objections to hiding barcode? 

![screen shot 2017-01-17 at 2 29 57 pm](https://cloud.githubusercontent.com/assets/4663357/22036496/c5636f0e-dcc1-11e6-93f6-2acf05297a7a.png)

**Comment by kmerguerian** [comment]
No objection, in fact I think having it display causes confusion. Especially since the call number is not labelled "call number" (a peeve I have with the old UI as well) and the barcode is surrounded by white space, so it's almost easier to see than the actual call number.  In this display the end user who hasn't used LC-classed collections before has no way of knowing which one of these is the number needed to find the book.

**Comment by winthropo** [comment]
That's something R&I needs to address then right?

**Comment by jasf-** [comment]
Confused - what does R&I need to address?

Not an R&I person any more, but I wonder if the phrase "call number" is meaningful to people who are confused by the difference between the barcode and the call number.

**Comment by winthropo** [comment]
Karen's point:

"In this display the end user who hasn't used LC-classed collections before has no way of knowing which one of these is the number needed to find the book."

If a student doesn't know the difference between a number labeled "barcode" and the call number it seems like an instruction issue to me -- R&I and IDEAS. No?

**Comment by kmerguerian** [comment]
Yes, and we can also meet them halfway by labelling Call Number.  Anyway, bottom line is we're agreeing the barcode can go from this display.

**Comment by winthropo** [comment]
We should file an enhancement if this isn't supported out-of-the-box.

**Comment by jasf-** [comment]
Sure.  But R&I and IDEAS will never reach all users, through instruction or otherwise.  So we need to design the system as best we can so that the 85%* of people who never interact w/ R&I or IDEAS can successfully locate stuff.

*made-up statistic

**Comment by winthropo** [comment]
If "design" means using the GUI back-end to improve the system I'm all for it -- editing mapping and code tables etc. . But we need to carefully examine, as a group, each JS/CSS customization proposal even if it existed in the old UI.

**Comment by jasf-** [comment]
Yes...but didn't this thread start w/ you asking if we could go ahead with hiding the barcode?  😁 

I'm going to show myself out now.

**Comment by winthropo** [comment]
It sure did, but then Karen brought up the call number and all heck broke out!!! 😄

**Comment by kflachs** [comment]
I agree that the barcode should be hidden.  It’s too confusing.

As for it not saying call number: you are talking about the line in the availability status? Available at :   [location] and then the call number that is in parenthesis.  Or are you talking about the listing of the real time availability data (the call number reference NOT in parenthesis.)

One, I wonder if we can add Call number.  We can add things to the end of the call number, so I think a norm rule might work.

But I also wonder if we need it, or if it is obvious, especially by the time students are searching a collegiate library.

The only catalogs where I’ve seen Call Number are for interfaces where a column structure is used (see MIT’s catalog- which is an EBSCOhost interface).  There is a column heading (that says Call Number) and then the call number is listed below.

Since in Primo, everything would be on one horizontal line, I think that could look odd.
It could also make the string be very long, in the case of the Available at:
Available at African American Institute Archives (E185.97.K5 A25 1987)and other locations

**Comment by kflachs** [comment]
I agree that the barcode should be hidden.  It’s too confusing.

As for it not saying call number: you are talking about the line in the availability status? Available at :   [location] and then the call number that is in parenthesis.  Or are you talking about the listing of the real time availability data (the call number reference NOT in parenthesis.)

One, I wonder if we can add Call number.  We can add things to the end of the call number, so I think a norm rule might work.

But I also wonder if we need it, or if it is obvious, especially by the time students are searching a collegiate library.

The only catalogs where I’ve seen Call Number are for interfaces where a column structure is used (see MIT’s catalog- which is an EBSCOhost interface).  There is a column heading (that says Call Number) and then the call number is listed below.

Since in Primo, everything would be on one horizontal line, I think that could look odd.
It could also make the string be very long, in the case of the Available at:
Available at African American Institute Archives (E185.97.K5 A25 1987)and other locations

**Comment by elizoller** [comment]
@nestochan &/or @gam looking at the alma iframe (ie. https://sandbox01-na.alma.exlibrisgroup.com/view/uresolver/01NEU_INST/openurl?ctx_enc=info:ofi/enc:UTF-8&ctx_id=10_1&ctx_tim=2017-02-14T13%253A26%253A37IST&ctx_ver=Z39.88-2004&url_ctx_fmt=info:ofi/fmt:kev:mtx:ctx&url_ver=Z39.88-2004&rfr_id=info:sid/primo.exlibrisgroup.com-NEU_ALMA&req_id=&rft_dat=ie=01NEU_INST:21228056760001401,language=eng,view=NUdev&svc_dat=getit&user_ip=&req.skin=nu-nui&env_type=test&is_new_ui=true&Force_direct=false) it looks to be using two stylesheets https://sandbox01-na.alma.exlibrisgroup.com/view/skins/default/css/otb_mashup_new.css?version=February2017_1 and https://sandbox01-na.alma.exlibrisgroup.com/view/branding_skin/css/mashup_new.css?skinName=nu-nui&version=February2017&skinVersion=1486411676&customerId=1390&institutionId=1401 
the mashup_new.css pulls in a file http://onesearch-test.neu.edu/primo_library/libweb/customized/newUI_uresolver.css - is that where i should be putting these css customization changes?

**Comment by winthropo** [comment]
For folks outside of LTS who might not know. We can't hide barcode in new UI and old UI at same time. So we will have to put up with barcode in new UI for time being until go-live.

**Comment by winthropo** [comment]
@nestochan fixed this. closing it.
