### ISSUE TITLE
Journal title search

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#250]
I do not see the journal title search offered in the new UI. In the old UI it is linked to the Advanced Search page.  

http://onesearch.northeastern.edu/primo_library/libweb/action/search.do?mode=Advanced&ct=AdvancedSearch&dscnt=0&vid=NU_JOURNALS

I can make it work as a search in the new UI using the following URL, but in this view, it is not presented/described as a journal title search.

http://northeastern-primostaging.hosted.exlibrisgroup.com/primo-explore/search?sortby=rank&vid=NU_JOURNALS&lang=en_US&mode=Advanced

**Comment by elizoller** [comment]
We'll need to decide where the link to the Journal Title Search will be.
Also the NU_JOURNALS view does not seem to be preselecting 'Title' and 'ISSN' like it does in the old UI. In the new UI the advanced search is closed by default so we might consider having it open by default for this view so the user can tell that they are on that view?

**Comment by winthropo** [comment]
FWIW. Here is BU's implementation. As far as I can tell they don't link to this from Primo. Just from their library page. I like the branding BU does.

Don't have a strong opinion about keeping advanced search open or closed by default. Tagged as a PUIG/READ discussion.

http://buprimo.hosted.exlibrisgroup.com/primo-explore/search?vid=journals&lang=en_US

**Comment by RPagani** [comment]
Per our PUIG/READ discussion today, I was thinking we could add the Journal Title Search in the bottom right corner of the Advanced Search (opposite of the Add a New Line feature):
<img width="1006" alt="add journal finder" src="https://cloud.githubusercontent.com/assets/25326379/22603591/05c01b72-ea16-11e6-8824-66ca131761ea.png">

Even when you have reached Advanced Search after typing in search terms, this placement should still look okay:
<img width="1070" alt="add journal finder img 2" src="https://cloud.githubusercontent.com/assets/25326379/22603628/26762c26-ea16-11e6-8680-403797772ef9.png">

Do we foresee any formatting issues with this placement?

**Comment by elizoller** [comment]
Currently the journal title search goes to a separate view with the scope set to library catalogs, the material type set to journals, and the first field set to title. I am wondering if its worth setting these parameters via angularjs instead of switching to a different view? i'm not seeing the benefit of using a different view. in the old ui this sort of manipulation of the page would have been difficult but with angular, it should be much simpler and less hack-y. in the mean time, i have implemented it in the new ui with the separate view as exists in the old ui.

**Comment by winthropo** [comment]
I like the angular approach. One less view. Thanks!
