### ISSUE TITLE
Enable Google Analytics for SOS new UI usage stats/info

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#298]
@kmerguerian can you set this up in Google Analytics for the new UI?

Scott

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/scholar-onesearch/commit/a3562d12821fb0baffcc3137b0fefb8d9461ec9c
looking in analytics, it shows up under the same site but if you go under Behavior > all pages and do an advanced search for begins with "/search" you will see the searches in the new ui (old UI has primo_library)
