### ISSUE TITLE
Report a Problem form not pre-populating info - May release

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#384]
Just started testing the May release.  

[This item ](http://onesearch-test.library.northeastern.edu/permalink/f/t09un1/TN_crossref10.1016/j.annemergmed.2018.05.010)in staging (May release) does not pre-populate info into Report a Problem form.

[Same item in production](https://onesearch.library.northeastern.edu/primo-explore/fulldisplay?docid=TN_sciversesciencedirect_elsevierS0196-0644(18)30432-3&context=PC&vid=NU&search_scope=default_scope&tab=default_tab&lang=en_US) does send pre-populate title into the Report a Problem form.

Both the brief and full record views show this behavior.

**Comment by gam5** [comment]
So it turns out there are multiple versions of this article available... if you go to the **exact** [same record](http://onesearch.library.northeastern.edu/primo-explore/fulldisplay?docid=TN_crossref10.1016%2Fj.annemergmed.2018.05.010&vid=NU&search_scope=default_scope&tab=default_tab&lang=en_US&context=PC) in production, you see the same behavior.

This record seems to be coming from crossref, but when I search for the article by keyword (second result for 'narcan'), the crossref version does not show up when I click "see all."

Both other versions work fine. It seems that there is some strange character encoding in the title of the crossref version. 

Do we know of any other examples where an item does not pre-populate info into the Report a Problem form? Production or sandbox.

**Comment by jasf-** [comment]
Apologies for the belated reply.  I just spent 15-ish minutes clicking around on various records in staging, even focusing on ones coming from CrossRef, and I can't find any other examples of this behavior.  Think I happened across an outlier before and I'm fine with closing this issue.
