### ISSUE TITLE
Changes to "home" page

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#60]
Content of home page needs updating, per Word document submitted under separate cover.

**Comment by bassettsj** [comment]
Below is the approved text for the homepage.

---

### How does this work?

Scholar OneSearch provides simple, one-stop searching for books and e-books, videos, articles, digital media, and more.  Search local Northeastern collections and global resources, with many items available in full text online. 

Scholar OneSearch also helps you manage your research.  Sign in with your myNEU credentials in order to: 
- Renew books and videos
- Create lists
- Export citations to Refworks and Endnote Web
- Order materials from other libraries.
- View full search results. (Some databases, like Web of Science, only show results when you're signed in.)

Questions? Comments? [Let us know what you think!](http://library.northeastern.edu/about/contact_us/)

---

### What am I searching?
- All books, e-books, videos, journals, and other collections from our legacy catalog, NUCat
- Articles, proceedings, and digital materials from a variety of licensed and open source databases. 
  If you only want items print materials located at Snell Library, the Law Library, and the African American Institute, limit your search by choosing "Library Catalogs" or "Law Library Catalog Only" from the drop-down menu. 

---

### Where can I get help?
- View our [Quick Guide (PDF)](http://library.northeastern.edu/sites/default/files/public/atttachments/FIELD_PAGE_FILES/2013/sos-quickguide.pdf)
- [Ask a librarian](http://library.northeastern.edu/ask) how to start your search
-  Dig deeper into library resources with [dedicated subject guides](http://subjectguides.lib.neu.edu/browse.php), which offer advice, recommendations, and contact information for subject librarians in your discipline.

**Comment by bassettsj** [comment]
![issue-60-homepage-changes](https://f.cloud.github.com/assets/1218420/1211610/37bba320-260c-11e3-9dcf-bb87bf5b0445.png)
[Leave Comments on Redpen.io](http://redpen.io/j8d1bg)
